Conf and relation
attrecto/Attrecto-Academy-JS-Backend-2021 pull request #1
Opened 2021-10-13 08:04 UTC by attrecto-mate-egyed

2021-10-13 08:04 UTC, attrecto-mate-egyed commented on src/config/config.service.ts
> +export class ConfigService {}
import elől

2021-10-13 08:15 UTC, attrecto-mate-egyed commented on src/database/entity/course.entity.ts
> +  @JoinColumn()
name: author_id, one to many

2021-10-14 07:22 UTC, martinhorvath1 commented
Az academy.db kell a repoba?
Illetve bekerült egy src/env.validation.ts üres fájl is ami szerintem szükségtelen

2021-10-14 07:22 UTC, martinhorvath1 requested changes

2021-10-14 07:22 UTC, martinhorvath1 commented on .env.example
> +NODE_ENV=local
A node env mint változó konvenció szerint 2 értéket vehet fel: 'development' és 'production' és ez nem azt jelenti, hogy milyen teszt környezeten fut, hanem azt, hogy az alkalmazás milyen módban fut (lokális futtatás esetén a development mód, erre hivatkozva tudunk bekapcsolni mondjuk extra debugging feature-öket, éles futtatás esetén pedig production mód) ebből adódik hogy a development meg a staging meg a production szerver node_env-je is konvenció szerint production.
Ha el akarjuk különíteni a teszt környezetet arra egy másik env változó bevezetése javasolt

2021-10-14 07:22 UTC, martinhorvath1 commented on src/app.module.ts
> +import { ConfigModule } from '@nestjs/config';
Az importoknál szoktunk tartani egy logikai sorrendet, ahol a külső függőséket (tehát brámi package-ből érkező) import előre kerül, aztán egy üres sor után jönnének a saját kódbázisból érkező importok

2021-10-14 07:22 UTC, martinhorvath1 commented on src/auth/auth.module.ts
> +import { ConfigService } from '@nestjs/config';
Az import sorrend itt is mint az app.module-nál

2021-10-14 07:22 UTC, martinhorvath1 commented on src/users/users.service.ts
> +import { ConfigService } from '@nestjs/config';
A config service-t felhasználod a fájlban? mert látszólag nem, viszont akkor felesleges az import is

2021-10-14 07:22 UTC, martinhorvath1 commented on src/database/entity/course.entity.ts
> +import { type } from 'os';
ez az import szerintem nem kell

2021-10-14 07:22 UTC, martinhorvath1 commented on src/users/dto/user.dto.ts
> +import { AssignCourseDto } from 'src/courses/dto/courses.dto';
itt ez az src alóli automatikus abszolút url-es import a VSCode által generált, bár működik, én a saját importot én itt inkább konzisztensen relatív útvonallal húznám be, hátha valahol gondotot okoz szerveren hogy nem tudja feloldani ezeket build után

2021-10-14 07:22 UTC, martinhorvath1 commented on src/courses/dto/courses.dto.ts
> +import {IsArray, IsNumber, IsOptional, IsString, IsUrl } from 'class-validator';
itt lemaradt sztem egy kis kód formázás, a { után célszerű tenni egy szóközt.
Amúgy kódformázásra a prettiert használjuk, be is van konfigolva a projektben elvileg by default, VSCode-hoz van plugin, érdemes azzal formázni mert az IDE-k között is konzisztens kódoformázást biztosít.

(van rá package.json-ben script is, npm run format, mert vscode extension aminek van billentyű kombinációja, mi még annyit szoktunk beletenni a projektben, hogy kommit előtt automatikusan formázzon hogy ne kerüljön be véletlenül sem formázatlan kód a repóba, de ez ide nem lett beépítve nyilván)

2021-10-14 07:22 UTC, martinhorvath1 commented on src/courses/courses.service.ts
> +    console.log(course);
A konzol log kivehető nem? vagy valami demonstrációs jelleg miatt maradt bent?

2021-10-14 07:22 UTC, martinhorvath1 commented on src/courses/dto/courses.dto.ts
>  export class CourseDto {
az importok után és a class előtt lehetne egy üres sor, hogy ketté válassza a részeket a szemnek

2021-10-14 07:22 UTC, martinhorvath1 commented on src/config/config.service.ts
> +export class ConfigService {}
Ezt a config service-t igazából nem is fogjuk haszálni sehol, nem? mert a nestjs/config által adott service lesz behúzva ahol konfig import van, szóval ez itt törölhető.

Így sztem config module tartalma is változhatna, mivel nem lesz benne semmi nest specifikus dolog, ezért config module.ts sem kell, és én így csinálnék a config mappa alatt 2 fájlt:
validation.ts -> ez tartalmaza a validate függvényt, amit aztán az app module behúz.
environment-variables.ts -> ez pedig az environment enumot és a EnvironmentVariables osztályt, ami definiálja a formátumát a konfignak
ez a service fájl pedig így törölhető is

2021-10-14 11:00 UTC, martinhorvath1 approved these changes

2021-10-14 11:01 UTC, martinhorvath1 commented on src/courses/dto/courses.dto.ts
> +  @IsNumber()
Ezt lehet, hogy lehetne szűkíteni IsInt meg IsPositive-ra

2021-10-15 10:16 UTC, merged